# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Plugin-QueriesTime
version:      0.01
version_from: lib/Class/DBI/Plugin/QueriesTime.pm
installdirs:  site
requires:
    Class::DBI:                    0
    Test::More:                    0.32
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
